FROM oven/bun:1.2.21 AS build
WORKDIR /app
COPY package*.json ./
RUN bun install --production
COPY . .
RUN bun run build


FROM nginx:alpine
RUN rm /etc/nginx/conf.d/*
COPY ./nginx.conf /etc/nginx/conf.d/
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

