services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - "9785:9785"
    image: "${SERVER_IMAGE}"
    restart: always

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    image: "${NGINX_IMAGE}"
    restart: always
