services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9785:9785"

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
