services:
  server:
    image: "${SERVER_IMAGE}"
    restart: always
    env_file:
      - .env
    ports:
      - "9785:9785"

  nginx:
    image: "${NGINX_IMAGE}"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
