version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: ${{ env.SERVER_IMAGE }}
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: ${{ env.NGINX_IMAGE }}
