version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: "${SERVER_IMAGE}"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: "${NGINX_IMAGE}"
