import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import { Navbar } from "../src/components";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
};

export default Home;
